version: 0.1

phases:
  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm run build-prod
  post_build:
    commands:
     # Clear S3 bucket.
      - aws s3 rm s3://cytel-react-application-poc/* --recursive
      - echo S3 bucket is cleared.    

artifacts:
  files:
    - build*/**
  discard-paths: yes
